gazebo_ros_control/pid_gains:
  joint_a1: {p: 10000.0, i: 0.03, d: 2.0}
  joint_a2: {p: 2500.0, i: 0.02, d: 50.0}
  # joint_a3: {p: 30000.0, i: 0.01, d: 2.0}
  # joint_a4: {p: 1500.0, i: 0.01, d: 10.0}
  # joint_a5: {p: 1000.0, i: 0.02, d: 1.0}
  # joint_a6: {p: 100.0, i: 10.0, d: 10.0}